apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "standalone.fullname" . }}
immutable: true
data:
  config.yaml: |
    version: 0.1
    spec:
      agent:
        kind: Default
        port: {{ .Values.agent.port }}
      state:
        kind: Default
        {{- if .Values.state.ttl }}
        ttl: {{ .Values.state.ttl }}
        {{end}}
        purge_interval: {{ .Values.state.purge_interval }}
      connection:
        kind: Default
        push_interval: {{ .Values.connection.push_interval }}
        pull_interval: {{ .Values.connection.pull_interval }}
        port: {{ .Values.connection.port }}
        r0: {{ .Values.connection.r0 }}
        timeout: {{ .Values.connection.timeout }}
        force_publish: {{ .Values.connection.force_publish }}
        peer_provider:
          kind: K8s
          selector:
            c19: {{ include "standalone.fullname" . }}
